### ISSUE TITLE
Support machine executor in job level invocation

### ISSUE THREAD

**Issue by eddiewebb** [eddiewebb/cci-shared-tasks#1]
Currently job expects a docker image as the executor, would like machine level support.

As a workaround, the command itself can be used this way.

```
orbs:
  common_tasks: eddiewebb/common_tasks@0.1.0
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - common_tasks/run_shared_task:
          task-name: demo-task


```
